service: lambda-tiler

provider:
  name: aws
  runtime: python3.6
  stage: production
  region: ${opt:region, 'us-east-1'}
  
  # Add optional bucket deployement
  # deploymentBucket: ${opt:bucket}


  environment:
    PYTHONWARNINGS: ignore
    GDAL_DATA: /var/task/share/gdal
    GDAL_CACHEMAX: 512
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 536870912
    CPL_TMPDIR: /tmp
    GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
    GDAL_HTTP_MULTIPLEX: YES
    GDAL_HTTP_VERSION: 2
    GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
    MAX_THREADS: 20

  # Add IAM Role statements to allow the tiler to access files
  # iamRoleStatements:
  #   -  Effect: "Allow"
  #     Action:
  #       - "s3:ListBucket"
  #       - "s3:GetObject"
  #     Resource:
  #       - "arn:aws:s3:::landsat-pds*"

  apiGateway:
    binaryMediaTypes:
      - '*/*'

package:
  artifact: package.zip

functions:
  lambda-tiler:
    handler: lambda_tiler.handler.APP
    memorySize: 1536
    timeout: 20
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true
